create database APIMOVIES
go
use APIMOVIES
GO
--TAO BANG NGUOIDUNg
create table TB_NGUOIDUNG
(
	MATAIKHOAN INT IDENTITY(1,1) 
			 CONSTRAINT PK_TAIKHOAN PRIMARY KEY,
	TENDANGNHAP NVARCHAR(20) NOT NULL,
	LOAITAIKHOAN NVARCHAR(20) NOT NULL,
	MATKHAU NVARCHAR(100) NOT NULL,
);
--TAO BANG LOAIPHIM
GO
create table TB_LOAIPHIM
(
	MALOAIPHIM INT IDENTITY(1,1) CONSTRAINT PK_LOAIPHIM PRIMARY KEY,
	TENLOAIPHIM NVARCHAR(20) NOT NULL,
);
GO
--TAO BANG PHIM
create table TB_PHIM
(
	MAPHIM INT IDENTITY(1,1) 
			 CONSTRAINT PK_PHIM PRIMARY KEY,
	TENPHIM NVARCHAR(100)  NULL,
	MOTAPHIM NVARCHAR(1000)  NULL,
	THOILUONG INT NOT NULL,
	ANH NVARCHAR(1000) NULL,
	NGONNGU NVARCHAR(100) NOT NULL,
	DUONGDAN NVARCHAR(100) NOT NULL,
	NAM INT NOT NULL,
	DANHGIAPHIM float NULL,
);
alter table TB_PHIM
alter column DANHGIAPHIM int NULL
go
-- Tao bang binh luan
create table TB_BINHLUAN
(
	MABINHLUAN INT IDENTITY(1,1) 
			 CONSTRAINT PK_BINHLUAN PRIMARY KEY,
	MATAIKHOAN INT  not null,
	MAPHIM INT NOT NULL,
	NOIDUNG nvarchar(100) null,
	THOIGIAN date null,
	CONSTRAINT FK_BINHLUAN_NGUOIDUNG FOREIGN KEY(MATAIKHOAN)
	REFERENCES TB_NGUOIDUNG(MATAIKHOAN)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT FK_TB_PHIM_BINHLUAN FOREIGN KEY(MAPHIM)
	REFERENCES TB_PHIM(MAPHIM)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
)
--Tao bang Phim Loai Phim
create table TB_Phim_LoaiPhim
(
	MA INT IDENTITY(1,1) 
			 CONSTRAINT PK_PHIM_lOAIPHIM PRIMARY KEY,
	MAPHIM INT  not null,
	MALOAIPHIM INT NOT NULL,
	CONSTRAINT FK_TB_LoaiPhim FOREIGN KEY(MALOAIPHIM)
	REFERENCES TB_LOAIPHIM(MALOAIPHIM)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT FK_TB_PHIM FOREIGN KEY(MAPHIM)
	REFERENCES TB_PHIM(MAPHIM)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
)
--TAO BANG LOAIPHIM
GO
create table TB_QUOCGIA
(
	MAQUOCGIA INT IDENTITY(1,1) CONSTRAINT PK_QUOCGIA PRIMARY KEY,
	TENQUOCGIA NVARCHAR(20) NOT NULL,
);
--Tao bang Phim QUOC GIA
create table TB_PHIM_QUOCGIA
(
	MA INT IDENTITY(1,1) 
			 CONSTRAINT PK_PHIM_QUOCGIA PRIMARY KEY,
	MAQUOCGIA INT  not null,
	MAPHIM INT NOT NULL,
	CONSTRAINT FK_TB_QUOCGIA FOREIGN KEY(MAQUOCGIA)
	REFERENCES TB_QUOCGIA(MAQUOCGIA)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT FK_TB_PHIM_QG FOREIGN KEY(MAPHIM)
	REFERENCES TB_PHIM(MAPHIM)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
)
